; Font styles
;   FONT_GOTHIC = 0
;   FONT_SUBTITLES = 1
;   FONT_MENU = 2
;   FONT_PRICEDOWN = 3

[MESSAGE]
; Default is 2000
; Message lifetime in milliseconds
; Specifies how long the message will stay on the screen
Message lifetime = 2000

; Default is 0.5
; Message opacity
; Value from 0.0 to 1.0, where 0.0 is fully transparent and 1.0 is fully opaque
Message opacity = 0.5

; Default is 0.5
; Message text size
; Value from 0.0 to 1.0, where 0.5 represents half of the standard text size
Message size = 0.5

; Default is 0
; Message color (Red component)
; Integer value from 0 to 255, where 0 is no red and 255 is full red
Message color R = 0

; Default is 255
; Message color (Green component)
; Integer value from 0 to 255, where 0 is no green and 255 is full green
Message color G = 255

; Default is 0
; Message color (Blue component)
; Integer value from 0 to 255, where 0 is no blue and 255 is full blue
Message color B = 0

; Give money for damaging cars
; If set to true, the player will receive money for damaging cars.
; Default is true
Give money for damaging cars = true

; Give money for exploding vehicles
; If set to true, the player will receive money for exploding vehicles. Doesn't give any money, if it's a player's vehicle.
; Default is true
Give money for exploding vehicles = true

; Show ammo count message
; If set to true, a message will pop up displaying how much ammo player picked up from the weapon pickup. Doesn't show a message, if no ammo is given.
; Default is true
Show ammo count message = true

; Default is 1
; Message font style
; Integer representing the font style to use for the message (0 for Gothic, 1 for Subtitles, 2 for Menu, 3 for Pricedown)
Message font style = 1

# Ammo messages
[WEAPON_MESSAGE]
; Weapon message opacity determines how transparent the message will be.
; Default value: 0.5 (50% transparency)
; Valid values: 0.0 (fully transparent) to 1.0 (fully opaque)
Weapon message opacity = 0.5

; Weapon message size defines the size of the text displayed.
; Default value: 0.5
Weapon message size = 0.5

; Weapon message color R (Red component of the text color).
; Default value: 0 (no red)
; Valid values: 0 to 255
Weapon message color R = 0

; Weapon message color G (Green component of the text color).
; Default value: 255 (full green)
; Valid values: 0 to 255
Weapon message color G = 255

; Weapon message color B (Blue component of the text color).
; Default value: 0 (no blue)
; Valid values: 0 to 255
Weapon message color B = 0

; Weapon message font style determines the font used for displaying the message.
; Default value: 1 (FONT_SUBTITLES)
Weapon message font style = 1
