[Settings]
; PT: Caso conflito com outro mod que também use CLEO vars, troque este número por outro entre 0 e 950. Alterar esse número num jogo que já foi salvo com achievements, causará problemas.
; EN: If it conflicts with another mod that also uses CLEO vars, change this number to another between 0 and 950. Changing this number in a already saved game with achievements will cause problems.
CleoVarIndex = 350
