[GFP]
fov = 90
hide_windshield_if_damaged = 0
hide_windshield_always = 0
hide_hood_if_damaged = 0
vehicle_free_mode_by_default = 0
fp_enabled_by_default = 0
invisible_mode_enable_in_vehicles_except_bikes = 1
smooth_mode = 1
smooth_mode_centering = 0
too_low = -0.4

key_change_view = 84                      ; T
key_toggle_free_mode = 66                 ; B
key_toggle_invisible_mode = 73            ; I
; key_zoom = 67                           ; C
key_look_out = 4                          ; MMB

offset_z = 0.06
offset_y_base = -0.04
offset_y = 0.15

near_clip_1 = 0.01
near_clip_2 = 0.05
; near_clip_override = 0.0
near_clip_invis = 0.10

assume_bald = 1
gamepad = 1

swim_above_water = 1

; key_offset_up = 33                        ; PAGE UP
; key_offset_down = 34                      ; PAGE DOWN
; key_offset_forward = 36                   ; HOME
; key_offset_back = 35                      ; END
; key_offset_left = 219                     ; [
; key_offset_right = 221                    ; ]
; key_offset_reset = 46                     ; DELETE
