[Settings]
;Default 8.0
BlipSize=8.0

;Sets then size of player blip that appears on map. Default 25.0
PlayerBlipSizeMap=6.5

;Sets then size of player blip that appears on radar. Default 8.0
PlayerBlipSizeRadar=8.0

;Sets the size of Airport Runway blip on map. Default 16.0
RunwayBlipSizeMap=16.0

;Sets the size of Airport Runway blip on radar. Default 16.0
RunwayBlipSizeRadar=16.0

;Sets the size of Airport Runway blip on radar when close to runway (animated). Default 8.0
RunwayBlipSizeRadarA=8.0

;Sets the animation speed of Airport Runway blip on radar. Default 3
;Higher is slower !!! It works backwards (1 is fastest, 100 is slowest).
RunwayBlipAnimSpeed=3