[MAIN]
# Toggle logging for debug purposes, (improves performance). Default is false.
Logging = false
# Maximum amount of bytes that can be written into the log file. Default is 9000000.
Max bytes in log = 9000000

# Define ambience intervals down below (in milliseconds). Default for minimum is 5000 and maximum is 10000.
# The mod will choose a random interval in the specified range (min, max) and wait X time to play the next ambience.

# Interior ambiences
Interior interval min = 10000
Interior interval max = 20000
# Generic ambiences
Ambience interval min = 5000
Ambience interval max = 10000
# Zone ambiences
Zone ambience interval min = 10000
Zone ambience interval max = 20000

# Define when distant sounds should trigger (in units).
# Default for gunshot is 50.0 and for explosions is 100.0.
# The distance is calculated from camera to the shooter.
Distant gunshot distance = 50.0
Distant explosion distance = 100.0

# Stereo ambience vol multiplier.
# Play around with the values to get the best result, since stereo ambience can be loud as hell.
# Default is 0.3
Stereo ambience volume = 0.3