
[MAIN]
# Max num of projectiles (aka array size). Default is 32.
NUM_PROJECTILES = 64

# Add your launchers down below (ID 512 max).
# Example:
# [GRENADE_LAUNCHERx] where x is the unique section ID. 
# If you need to add more than one grenade launcher - increase the number in the container (for example, [GRENADE_LAUNCHER2], [GRENADE_LAUNCHER3] and etc.)
# WEAPON_ID is the weapon type (NOT MODEL ID) of the launcher.
# PROJECTILE_MODEL_ID speaks for itself, it's the projectile model id that will be launched.
# FORCE is the force that the projectile will be propelled with.
# PROJECTILE_STREAK determines whenever there's a streak needed to be drawn behind the projectile.
# PROJECTILE_STUCKING determines whenever the projectile should get stuck in the surface if the distance between the shooter and the gun is too close.
# (PROJECTILE_TYPE doesn't work)
# PROJECTILE_IMPACT_TYPE - type of explosion after projectile is triggered (https://www.gtag.sannybuilder.com/sanandreas/explosions)
# PROJECTILE_GRAVITY - projectile gravitation. If FALSE - projectile will not change trajectory in air by gravity.
# PROJECTILE_PARTICLE - attached particle. Use name from EFFECTS.FXP not ID or from this site - https://www.gtag.sannybuilder.com/sanandreas/particles

[GRENADE_LAUNCHER1]
# your weapon ID (not weapon model ID) here - you can get it from "data\gtasa_weapon_config.dat"
WEAPON_ID=97

# your projectile model ID
PROJECTILE_MODEL_ID=11418

FORCE = 1.25
PROJECTILE_STREAK = true
PROJECTILE_STUCKING = true
PROJECTILE_IMPACT_TYPE = 0
PROJECTILE_GRAVITY = true

#particle name here (EFFECTS.FXP)
PROJECTILE_PARTICLE=prt_smokeII_3_expand
[GRENADE_LAUNCHER2]
# your weapon ID (not weapon model ID) here - you can get it from "data\gtasa_weapon_config.dat"
WEAPON_ID=94

# your projectile model ID
PROJECTILE_MODEL_ID=11419

FORCE = 1.55
PROJECTILE_STREAK = true
PROJECTILE_STUCKING = true
PROJECTILE_IMPACT_TYPE = 0
PROJECTILE_GRAVITY = true

#particle name here (EFFECTS.FXP)
PROJECTILE_PARTICLE=prt_smokeII_3_expand