; map_ambience.ini
; Define ambiences around the map in this .ini file!
; Sections: [Ambience0], [Ambience1], ...
; Keys:
;   File  = path to audio file relative to generic/ambience (or absolute). You can define more than one file in single section. For example:
;   file.wav, fileA.wav, fileB.wav, /path1/path2/file.wav etc.
;   USE "/" SLASH ONLY!!!
;   Keep in mind, looped ambiences only require a single sound, more than one can't be added.
;   X/Y/Z = world coordinates
;   Range = the sphere radius in which the ambience will be active (if player left it, it will stop playing)
;   Loop  = false or true  (if true, ambience will loop while player inside it's range)
;   Time  = day|night|riot|any    (optional, default any. Determines when will this ambience play. NOTE: Riot doesn't work in interiors)
;   Delay = integer, in milliseconds (When will the next ambience play, works only if it's not a looped ambience, which is only a one file).
;
; * Source maximum distance.
; * Range:   [0.0 - ]
; * Default: 50.0
; *
; * The distance above which the source is not attenuated any further with a
; * clamped distance model, or where attenuation reaches 0.0 gain for linear
; * distance models with a default rolloff factor.
;
;   Max distance attenuation = 50.0
;
;
;
; * Source reference distance.
; * Range:   [0.0 - ]
; * Default: 1.0
; *
; * The distance in units that no distance attenuation occurs.
; *
; * At 0.0, no distance attenuation occurs with non-linear attenuation models.
;   Reference distance = 1.0
;
;
;
; * Source rolloff factor.
; * Range:   [0.0 - ]
; * Default: 1.0
; *
; * Multiplier to exaggerate or diminish distance attenuation.
; *
; * At 0.0, no distance attenuation ever occurs.
;   Roll off factor = 1.0


; Air absorption simulates sound energy loss over distance,
; especially high frequencies, 
; making distant sounds quieter, more muffled and duller.
; Default is 1.0

; Pure examples, set your own.
[Ambience0]
File = thunder0.wav, ambience2.wav
X = 0.0
Y = 0.0
Z = 13.0
Range = 30.0
Loop = false
Time = any
Delay = 10000
Max distance attenuation = 50.0
Reference distance = 1.0
Roll off factor = 1.0
Air absorption = 1.0
Allow other ambiences = false

[Ambience1]
File = ambience2.mp3
X = -2423.459961
Y = -729.224243
Z = 150.132812
Range = 150.0
Loop = true
Time = any
Delay = 0
Max distance attenuation = 50.0
Reference distance = 1.0
Roll off factor = 1.0
Air absorption = 1.0
Allow other ambiences = true

[Ambience2]
File = 535 Ambients.wav
X = 2393.536621
Y = -1641.041260
Z = 14.209984
Range = 50.0
Loop = true
Time = any
Delay = 0
Max distance attenuation = 700.0
Reference distance = 1.8
Roll off factor = 1.0
Air absorption = 1.0
Allow other ambiences = true

[Ambience3]
File = drips.wav
X = 201.818314
Y = 1873.485229
Z = 15.107983
Range = 35.0
Loop = true
Time = any
Delay = 0
Max distance attenuation = 130.0
Reference distance = 1.3
Roll off factor = 1.0
Air absorption = 1.0
Allow other ambiences = true

[Ambience4]
File = computalk1.wav, computalk2.wav
X = 212.416290
Y = 1822.844116
Z = 6.414062
Range = 15.0
Loop = false
Time = any
Delay = 1500
Max distance attenuation = 150.0
Reference distance = 1.3
Roll off factor = 1.5
Air absorption = 1.0
Allow other ambiences = false

[Ambience5]
File = interiors/18/X7_11B/ambience0.wav, interiors/18/X7_11B/ambience1.wav, interiors/18/X7_11B/ambience2.wav
X = -26.046082
Y = -82.828964
Z = 1013.852722
Range = 30.0
Loop = false
Time = any
Delay = 3000
Max distance attenuation = 30.0
Reference distance = 1.8
Roll off factor = 1.0
Air absorption = 1.0
Allow other ambiences = true