[MAIN]
# Vanilla game value is 300
Number of shopping items = 1024
# Vanilla game value is 300
Number of shopping items per shop = 1024
# Vanilla game value is 4 (probably unnecessary to modify, only those two above should concern you)
Number of modifiable stats = 4
