[SA.StoriesSprinting]
; Lines beginning with ";" are ignored.
; If the script can't read a setting, it'll use the default value for it.

; Disables the fat variation of the handgun run walkstyle. Set it to 1 to disable it. 0 by default:
NoFat1Armed=0

; Disables the muscular variation of the handgun run walkstyle. Set it to 1 to disable it. 0 by default:
NoMuscle1Armed=0

; Enables the Fire Extinguisher walkstyle fix, making CJ use the Chainsaw/Flamethrower/Minigun walkstyle when holding it. Set it to 0 to disable it. 0 by default:
FireExtinguisherWalkstyleFix=1

; Weapon list for handgun run walkstyle. The handgun run walkstyle is already applied on pistols, SMGs and some melee weapons. You can add a new weapon id here.
Weapon1 = 2     ; Golf stick
Weapon2 = 8     ; Katana
Weapon3 = 10    ; Long dildo
Weapon4 = 12    ; Long vibrator
Weapon5 = 14    ; Flower
Weapon6 = 15    ; Cane
Weapon7 = 26    ; Sawnoff shotgun
Weapon8 = 43    ; Camera
Weapon9 = 71    ; Tribarrel
Weapon10 = 72   ; Peppergun
Weapon11 = 75   ; Harvest dagger
Weapon12 = 76   ; Kukri
Weapon13 = 79   ; Machete
Weapon14 = 80   ; Hockey stick
Weapon15 = 85   ; Fasthawk
Weapon16 = 86   ; Sword
Weapon17 = 87   ; Woodman
Weapon18 = 89   ; Woodman
Weapon19 = 91   ; Woodman
Weapon20 = 92   ; Woodman
Weapon21 = 93   ; Woodman
Weapon22 = 95   ; Woodman
Weapon23 = 98   ; Woodman
Weapon24 = 99   ; Woodman
Weapon25 = 102  ; Woodman
Weapon26 = 104  ; Woodman
Weapon27 = 105  ; Woodman
Weapon28 = 106  ; Woodman
Weapon29 = 107  ; Woodman