------------------------ Double Reload Fix v.26.02.16 -----------------------

; During gameplay, type "DRFRELOAD" to reload the settings

[SETTINGS]

DisableOnSAMP = 0        ; 0 = Enabled. // 1 = Deactivates this mod when playing SAMP.

DualWieldFix = 1         ; With dual-wielded weapons, CJ will only receive half of the ammo if he only managed to reload one weapon.


[WEAPONCONFIG]           ; Here you can configure the reload settings for each weapon. You can add weapons to this list.

; Format: 'Weapon ID' (not model ID) = 'Reload Progress' / Reload Speed by skill level: 'Poor' / 'Gangster' / 'Hitman'

; 'Weapon ID'       = weapon number: https://wiki.multitheftauto.com/wiki/Weapons
; 'Reload Progress' = Represents the required animation progress of the reload anim to be considered complete, preventing the double reload bug
;                     1.0 means after full progress of animation (= vanilla), 0.5 for half etc.
; 'Reload Speed'    = Reload animation speed for the respective skill levels. Weapons without skill levels (such as Sniper and Minigun) are always 'Gangster'.

Default = 0.40 / 1.00 / 1.25 / 1.50   ; Setting for all weapons that aren't configured below

22 = 0.40 / 1.00 / 1.20 / 1.40   ; Colt 45

27 = 0.50 / 1.00 / 1.25 / 1.50   ; Combat Shotgun

28 = 0.40 / 1.20 / 1.40 / 1.60   ; Uzi
29 = 0.30 / 1.00 / 1.25 / 1.50   ; MP5
32 = 0.40 / 1.10 / 1.30 / 1.50   ; Tec-9

30 = 0.40 / 1.00 / 1.20 / 1.40   ; AK-47
31 = 0.40 / 1.20 / 1.40 / 1.60   ; M4

33 = 0.50 / 0.00 / 1.80 / 0.00   ; Rifle
