------------------------ EasyThrow v.26.05.23 -----------------------

[SETTINGS]

DisableOnSAMP = 0    ; 0 = Enabled. // 1 = Deactivates this mod when playing SAMP.


; Type key names, such as G, or + (it detects common keys) or virtual keycodes greater than 9

ThrowKey      = 5
DetonateKey   = 6    ; For Satchel Detonator
