# Improved Jetpack Control Mod by Junior_Djjr - MixMods.com.br
[Settings]
THRUST_FULL          = 4.0   # (0.6) Acceleration speed.
THRUST_STRAFE        = 2.0   # (0.3) Acceleration speed to the side.
THRUST_ANTIGRAVITY   = 0.001 # (0.008) Force against gravity when accelerating. Smaller numbers have more gravity.
LEG_SWING_DAMP_FRAC  = 0.8   # (0.98) Leg movement sensitivity. Recommended to lower when increased speed.
THRUST_NOMINAL       = 1.0   # (0.8) Constant brake.
BRAKE_DIV            = -0.5  # (0.5) Brake division. The less, the more brake. Accepts negative values.