[Settings]
ShootingRate=100
Accuracy=100
FightingStyle=5
AttackMoves=6
HearingRange=75.0
SeeingRange=150.0
DmNumPedsToScan=9
DmRadius=45.789456
Health=1000.0
MaxHealth=1000.0
Armor=1000.0


#Set weapon for newly-recruited unarmed gang members
#Default values 22 200 1
WeaponID=30 #32
Ammo=999
Skill=2

#Use cheat GANGUPD to update the settings during gameplay

####################################
#	Fighting Styles
#	 Default = 4
#	 Boxing = 5
#	 KungFu = 6
#	 KickBoxing = 7
#	 Bat = 8
#	 Knife = 9
#	 GolfClub = 10
#	 Katana = 11
#	 Chainsaw = 12
#	 Dildo = 13
#	 NotCombos = 14
#	 YesCombos = 15
#	 Elbows = 16

#	Attack Moves
#	 ClearAll = 0
#	 Unknown1 = 1
#	 Unknown2 = 2
#	 Unknown3 = 3
#	 Unknown4 = 4
#	 Unknown5 = 5
#	 All = 6
#
#DmRadius - decision making radius
#Vanilla values
#  ped->m_fHealth = 100.0;
#  ped->m_fMaxHealth = 100.0;
#  ped->m_fArmour = 0.0;
#  this->m_fHearingRange = 15.0;
#  this->m_fSeeingRange = 15.0;
#  this->m_dwDmNumPedsToScan = 3;
#  this->m_fDmRadius = 15.0
#  this->m_fSeeingRange = 40.0;
#  this->m_fHearingRange = 40.0;