# "REARLIGHT1" and "REARLIGHT2" cheat code for reload settings



[Red Line]
Red Line = 0				# 1 - enable, 0 - disable
Red Line for Bike = 0			# 1 - enable, 0 - disable (Nitro)
Intensity Y = 0.005			# default 0.004
Intensity Z = 0.01			# default 0.01
Alpha = 0.0				# 0.0 - 1.0
Alpha Nitro = 0.2			# 0.0 - 1.0
Divided Speed = 125.0			# default 125.0



[TailLight]
TailLight = 1				# 1 - enable, 0 - disable
TailLight Alpha = 60			# 0 - 255
TailLight Alpha Nitro = 20		# 0 - 255
TailLight Size = 1.3			# default 1.3
TailLight Size Nitro = 1.3		# default 1.5



[Wind Effect]
Wind Effect = 0				# 1 - Only with nitro, 2 - Always, 0 - disable
Last Factor = 0.2			# 0.0 - 1.0



[Reverse gear]
Reverse gear = 1			# 1 - enable, 0 - disable
Size = 0.3				# default 0.3



[Screen Effects With Nitro]
FOV = 1					# 1 - enable, 0 - disable. 
FOV in SAMP = 0				# 1 - enable, 0 - disable. first enable FOV = 1
FOV Widescreen Fix 2024 = 1		# 1 - enable, 0 - disable. If you are using the old ver - disable
Camera Shake = 1			# 1 - enable, 0 - disable



[Light On The Ground]
Light On The Ground = 1			# 1 - enable, 0 - disable
Size = 1.1				# default 1.1
Size Bike = 1.4				# default 1.4
Light = 45				# 0 - 255



[NPC Cars Red Line]
Red Line = 0				# 1 - enable, 0 - disable. For NPC or SAMP
Intensity Y = 0.002			# default 0.002
Intensity Z = 0.005			# default 0.005
Divided Speed = 2.0			# default 2.0
Alpha = 0.4				# 0.0 - 1.0
Alpha Nitro = 0.8			# 0.0 - 1.0