[Settings]
;Sets zoom level when you zoom for the first time. Default 70.0 (no zoom).
DefaultZoom=50.0

;Sets the model Id for weap 1
;Set to -1 to disable weap 1
Weap1=74

;Sets maximum zoom level for weap 1(lower=more zoom). Default is 15.0
MaxZoom1=9.5

;Sets the model Id for weap 2
;Set to -1 to disable weap 2
Weap2=81

;Sets maximum zoom level for weap 2 (lower=more zoom). Default is 15.0
MaxZoom2=1.65

;Sets the model Id for weap 3
;Set to -1 to disable weap 3
Weap3=96

;Sets maximum zoom level for weap 3 (lower=more zoom). Default is 15.0
MaxZoom3=5.3

;Sets the model Id for weap 4
;Set to -1 to disable weap 4
Weap4=101

;Sets maximum zoom level for weap 4 (lower=more zoom). Default is 15.0
MaxZoom4=15.0

;Sets the model Id for weap 5
;Set to -1 to disable weap 5
Weap5=34

;Sets maximum zoom level for weap 5 (lower=more zoom). Default is 15.0
MaxZoom5=15.0

;Sets the model Id for weap 6
;Set to -1 to disable weap 6
Weap6=-1

;Sets maximum zoom level for weap 7 (lower=more zoom). Default is 15.0
MaxZoom6=34.0

;Rate of zoom change on mouse wheel scroll
ZoomChangeRatio=5.0

;If set to 1, then zoom level will be stored and next time you aim with sniper - zoom will be
;set to that level. Set to 0 to always use DefaultZoom value.
UseSameZoom=0

;Set to your preferred key code and when holding that key and scrolling mouse
;wheel zoom change ratio will be set to 1.0
;Set to -1 to disable this function
FineTuneKey=192

;If set to 1 then the script will display zoom level (FOV level, actually).
DebugShowZoomLvl=0