# by Junior_Djjr - MixMods.com.br
# Use Crash List: https://www.mixmods.com.br/p/lista-de-crash-e-solucoes.html

[Settings] 
# 1 = World
# 2 = LS
# 3 = SF
# 4 = LV
Local = 1

Speed = 1.5 

RotateCamera = 1
CameraSpeed = 20.0

DisableWanted = 1

[SimpleLog]
# This is the last position. If crashed last time, maybe this helps to understand the reason.
LastCoordX =1628.1
LastCoordY =955.804
