# Use cheat "RSWRA" to reload this settings file

[Settings]
iRecoilMode = 0 # default recoil mode, see sections [RecoilMode_WeaponIDs] and [RecoilMode_AnimGroupIDs]

# allowed directions for recoil | 0: left, right, up | 1: up only | 2: left, right, up, down | 3: taps
# taps: recoil will start at the top and diverge horizontally the longer you shoot, stop shooting to let it 'cool down'

[Toggles]
# comment out or use 0 to disable | uncomment and use any other value to enable
; bNoCrosshairSpread = 1 # no crosshair spreading when shooting (like nospread)
; bNoAimCheck = 1 # no aim check when firing, i.e, recoil still occurs when shooting without aiming
; bNoCrosshairReturn = 1 # crosshair will not gradually return to position of last shot
; bNoAdditiveRecoil = 1 # crosshair will not gradually return to position of first shot instead of last for iRecoilMode = 1 , requires bNoCrosshairReturn = 0
; bForceAim = 1 # force aiming as long as crosshair is returning, emulates button press, requires bNoCrosshairReturn = 0 and bNoAimCheck = 0

# WeaponFireTypes, WeaponIDs and AnimGroupIDs have highest ID limit of 999

[WeaponFireTypes]
# enabled weapon firetypes | format: WeaponFireType = any non-zero value | WeaponFireTypes taken from https://gtamods.com/wiki/Weapon.dat#San_Andreas
; 1 = 1 # INSTANT_HIT | hard-coded: uncomment and use 0 disable
; 2 = 1 # PROJECTILE | hard-coded: uncomment and use 0 disable



# recoil multiplers in float | use 0 or less to disable | note that the values are multiplicative

[RecoilMultipliers]
fGlobal = 1.2
fStopped = 0.75
fCrouching = 0.75
fSingleHanded = 1.25 # single-handed weapons (with flag CANAIM)
fDualWield = 1.5 # dual wielded weapons (with flag TWIN_PISTOL)
fDriveBy = 1.0

[Misc]
fCrosshairReturnSpeed = 0.001 # speed at which crosshair will return to point of last shot, requires bNoCrosshairReturn to be disabled
fAccuracyThreshold = 10.0 # if weapon accuracy limit is higher than this value, recoil will not occur

[WeaponIDs]
# format: WeaponID = recoil multiplier, WeaponIDs taken from http://hotmist.ddo.jp/id/weapon.html

38 = 2.0

[AnimGroupIDs]
# format: AnimGroupID = recoil multiplier, AnimGroupIDs taken from http://gtamodding.ru/wiki/%D0%90%D0%B4%D1%80%D0%B5%D1%81%D0%B0_%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%B8_(SA)#WEAPON.DAT

31 = 0.25 # spraycan
30 = 10.0 # rocket
27 = 2.5 # sniper
15 = 0.75 # colt45pro
20 = 4.0 # shotgunbad
19 = 4.0 # shotgun
29 = 0.25 # flame
12 = 3.0 # pythonbad
11 = 3.0 # python
23 = 1.5 # uzi
21 = 2.0 # buddy
22 = 3.0 # buddybad

# ID-specific return speed, priority order: WeaponID > AnimGroupID > Default

[ReturnSpeed_WeaponIDs]
# format: WeaponID = return speed

38 = 0.005 # SNIPER

[ReturnSpeed_AnimGroupIDs]
# format: AnimGroupID = return speed

30 = 0.005 # rocket
27 = 0.0005 # sniper
15 = 0.0025 # colt45pro
19 = 0.0015 # shotgun	
23 = 0.00125 # uzi
24 = 0.00125 # uzibad
21 = 0.0003 # buddy
22 = 0.0005 # buddybad

[RecoilMode_WeaponIDs]
# format: WeaponID = iRecoilMode



[RecoilMode_AnimGroupIDs]
# format: AnimGroupID = iRecoilMode

15 = 3 # colt45pro
25 = 3 # rifle
27 = 1 # sniper
20 = 2 # shotgunbad
30 = 2 # rocket
11 = 1 # python
17 = 2 # sawnoffpro
29 = 2 # flame
18 = 1 # silenced
23 = 3 # uzi
21 = 2 # buddybad
31 = 2 # spraycan