; Car Dealer
; by rill_

[Config]
Docks = 0               ; 0 = disable, 1 = enable. Enable or disable dealers at docks.
GrottiShowroom = 1      ; Set to 1 if you have Proper Fixes v2.0.1
UnlockAll = 0           ; 0 = disable, 1 = enable. Unlock A and S tier vehicles from the beginning. Updated realtime.
ExportPayoutMult = 1.0  ; Export payout multiplier. Updated realtime.

; You can type "NEXTWEEKISOURWEEK" to refresh the export request. It's count as a cheat.
; You can reload below settings by re-enter the showroom.

[BGM]
; Max 99 characters
Directory = cleo/Assoluto Racing OST - Dealership - Julien Mt.mp3
Volume = 0.3
3DEffect = 0            ; 0 = disable, 1 = enable

[Stats]
; Type "CARSTAT" while on a vehicle to reload this section settings.
; Button lists are at the bottom of this file.
; Set -1 to disable.
KeyboardKey = 9         ; Default = 9 (TAB)
JoypadKey = 9           ; Default = 4 (LEFTSHOULDER1)
PosX = 90.0
PosY = 260.0
ShowSeed = 1            ; 0 = disable, 1 = enable. Show vehicle's seed. Seed value is "Extras 3" in vehicle options.
; Stats multiplier
TopSpeed = 1.0
Acceleration = 1.0
Handling = 1.0
Brake = 1.0

; Format : (normal) (poorfamily) (richfamily) (executive) (motorbike) (moped)
; 0 = exclude, 1 = include
; Quadbikes are recognized as motorbike class
; You can forcibly add some vehicles that are not included in the class by put it's model name.
; You can ignore some vehicles that included in the class by put it's model name.

; Interior numbers
; 0 = Default (unused warehouse)
; 1 = Asphalt 8 showroom. Download here: https://libertycity.net/files/gta-san-andreas/204984-the-showroom-from-asphalt-8.html
; 2 = Vinewood Car Club. Download here: https://libertycity.net/files/gta-san-andreas/219058-gta-online-the-vinewood-car-club.html
; 3 = Workshop. Download here: https://libertycity.net/files/gta-san-andreas/173397-%D9%88%D8%B1%D8%B4%D8%A9-%D8%B9%D9%85%D9%84.html
; 4 = CSR Racing 2 Garage. Download here: https://sharemods.com/bd4mebnn19pv/CSR_Racing_2_Garage.7z.html
; IMPORTANT!! Make sure you followed the installation instructions inside the Car Dealer's mod archive before setting those added interiors!!
[Coutt and Schutz]
Interior = 0
Class = 1 1 0 0 0 0
;Model1 = taxi
;Model2 = pfister
;Model3 = copbike
;Model4 = nrg500
;Model5 = hayabusa
;Model6 = uranus
;Model7 = rg21
;Model8 = yellowbr
;Model9 = itali
;Model10 = quad
;Model11 = orion
;Model12 = infernus
;Ignore1 = peren

[Grotti]
Interior = 0
Class = 0 0 1 1 0 0
;Model1 = nrg500

[Ocean Docks]
Class = 1 1 1 1 1 1
;Model1 = petro
;Model2 = rhino

[Wang Cars]
Interior = -1
Class = 0 0 1 1 0 0

[Otto's Autos]
Class = 0 0 0 1 0 0

[Easter Basin]
Class = 1 1 1 1 1 1
;Model1 = monster

[Shody]
Interior = 0
Class = 1 1 0 0 1 1

[Autobahn]
Interior = 0
Class = 1 0 1 1 0 0

; These models are only ignored by class filter. They still can be included by defining it's model name in the dealers' section above.
[Ignore]
Model1 = romero
Model2 = pizzaboy
Model3 = caddy
Model4 = baggage
Model5 = nrg500
Model6 = tractor
Model7 = tug
Model8 = glenshit
Model9 = sadlshit
Model10 = rnchlure
Model11 = sightsee
Model12 = manticr
Model13 = bustran
Model14 = transmas
Model15 = darshit
Model16 = aeroline
Model17 = oraclepz
Model18 = lguard
Model19 = defianm
Model20 = grmshit
Model21 = elwdshit
Model22 = pizdink
Model23 = cb500rs

; Joypad buttons
; 0 LEFTSTICKX
; 1 LEFTSTICKY
; 2 RIGHTSTICKX
; 3 RIGHTSTICKY
; 4 LEFTSHOULDER1
; 5 LEFTSHOULDER2
; 6 RIGHTSHOULDER1
; 7 RIGHTSHOULDER2
; 8 DPADUP
; 9 DPADDOWN
; 10 DPADLEFT
; 11 DPADRIGHT
; 12 START
; 13 SELECT
; 14 SQUARE
; 15 TRIANGLE
; 16 CROSS
; 17 CIRCLE
; 18 LEFTSHOCK
; 19 RIGHTSHOCK

; Keyboard keys																										
; 8	=>	Backspace                    57	=>	9						 92		=>	(right Windows key)		123	=>	F12
; 9	=>	Tab                          65	=>	A						 93		=>	(application key)		144	=>	Num Lock
; 13	=>	Enter                    66	=>	B                        96		=>	0 (numpad)				145	=>	Scroll Lock
; 16	=>	Shift (both)             67	=>	C                        97		=>	1 (numpad)          	186	=>	;
; 17	=>	Ctrl (both)              68	=>	D                        98		=>	2 (numpad)          	187	=>	=
; 19	=>	Pause                    69	=>	E                        99		=>	3 (numpad)          	188	=>	,
; 20	=>	Caps Lock                70	=>	F                        100	=>	4 (numpad)          	189	=>	-
; 27	=>	Esc                      71	=>	G                        101	=>	5 (numpad)          	190	=>	.
; 32	=>	Spacebar                 72	=>	H                        102	=>	6 (numpad)          	191	=>	/
; 33	=>	Page Up                  73	=>	I                        103	=>	7 (numpad)          	192	=>	`
; 34	=>	Page Down                74	=>	J                        104	=>	8 (numpad)          	219	=>	[
; 35	=>	End                      75	=>	K                        105	=>	9 (numpad)          	220	=>	\
; 36	=>	Home                     76	=>	L                        106	=>	* (numpad)          	221	=>	]
; 37	=>	(left arrow)             77	=>	M                        107	=>	+ (numpad)          	222	=>	'
; 38	=>	(up arrow)               78	=>	N                        109	=>	- (numpad)
; 39	=>	(right arrow)            79	=>	O                        110	=>	. (numpad)
; 40	=>	(down arrow)             80	=>	P                        111	=>	/ (numpad)
; 45	=>	Insert                   81	=>	Q                        112	=>	F1
; 46	=>	Delete                   82	=>	R                        113	=>	F2
; 48	=>	0                        83	=>	S                        114	=>	F3
; 49	=>	1                        84	=>	T                        115	=>	F4
; 50	=>	2                        85	=>	U                        116	=>	F5
; 51	=>	3                        86	=>	V                        117	=>	F6
; 52	=>	4                        87	=>	W                        118	=>	F7
; 53	=>	5                        88	=>	X                        119	=>	F8
; 54	=>	6                        89	=>	Y                        120	=>	F9
; 55	=>	7                        90	=>	Z                        121	=>	F10
; 56	=>	8                        91	=>	(left Windows key)       122	=>	F11