;-------------------------------------------------------------------------;
; Proper Shaders mod by Junior_Djjr - MixMods.com.br - Patreon.com/Djjr   ;
; You can reload this file by typing 'PSRLD' like a cheat.                ;
;-------------------------------------------------------------------------;

[Base]
EnabledMod = 1           ; Set 0 to completely disable this mod.
LogLevel = 3             ; 1 = Only errors; 2 = Errors and warnings; 3 = All infos;
UseD3D9Proxy = 1         ; Use a D3D9 proxy. This is required for lots of features. Only disable it if you REALLY need it (for compatibility issues).
GenerateDepthBuffer = 1  ; Generates a Z depth buffer. This is required for lots of features. Only disable it if you REALLY need it (for compatibility issues).
ReversedDepthBuffer = 1  ; Reverses the Z depth buffer. This dramatically improves the game's z-fighting problems (nearby faces flickering, especially at a distance). Only disable it if you REALLY need it (for compatibility issues).

; Pipeline is the system behind the game's rendering. Here you can choose which one to use it, or leave it at "0" to not change anything. This is what's needed for the mod's main features, such as shadows that requires "lit".
[Pipelines]
Map = 1       ; 0 = PC unlit; 1 = PS2 lit
Vehicles = 1  ; 0 = PC unlit; 1 = PS2 lit
Skins = 1     ; 0 = PC unlit; 1 = PC lit

[Shadows]
Enabled = 1                     ; Set 1 to enable per-pixel dynamic shadows. 
Resolution = 8192               ; Shadow resolution. 4096 is generally a good number, but you can try 8192 if your GPU is powerful or for "photo mode". If cascade is enabled, this is the atlas resolution (each cascade will use half).
PCSS = 1                        ; Use NVIDIA's PCSS (Percentage-Closer Soft Shadows) algorithm. Slightly more resource-intensive, but it makes the shadows a bit more realistic (the base will be sharper, softer in distant projections).
Cascaded = 0                    ; Use 4 cascades of shadows for high-resolution close-up shadows, with lower-resolution shadows at a distance. This significantly increases CPU and GPU usage, specially on this engine, therefore, don't enable it on weak or even mid-range PCs.
MaxDistance = 250               ; Shadows range distance in meters. More distant shadows consume more resources, and the quality is compromised, requiring an increase in resolution to avoid pixelated shadows. Generally, 200 or 300 are good numbers.
MaxDistanceNightMult = 0.7      ; Multiplier for "MaxDistance" during night time.
SearchObjectsRadiusMult = 0.8   ; Distance multiplier for including objects in shadow capture. This is an important fine-tuning adjustment for performance. Increasing it (e.g. 1.2) prevents shadow pops, while lowering it (e.g. 0.8) can improve performance but may cause shadow pops. Use "DebugTextures = 1" to test it.
SearchObjectsFrustumMult = 0.8  ; Idem above. For frustum culling width/height.
SearchObjectsFarPlaneMult = 0.8 ; Idem above. For frustum culling range distance.
Softness = 1.2                  ; Multiplier to create softer or sharper shadows. Note that there is currently no Gaussian blur (due to technical reasons), therefore the softness has banding and is not the best visuals. It's best to avoid using high values.
NormalBiasMult = 2.0            ; Multiply the bias (offset) to avoid shadow acne on walls etc. This value should be as low as possible to avoid light leaking, specially near the roofs, but high enough to avoid incorrect shadows on angles. This option uses the mesh normals, which are quite poor in the vanilla game (Proper Fixes will improve this), so don't use high values.
DepthBiasMult = 3.0             ; Same as before, but a simple depth offset.
DetailedModelsBiasMult = 0.8    ; Multiply the bias for detailed models (vehicles, skins). It's generally a good idea to lower it slightly, as they have more fine details. For normals.
DetailedModelsSoftMult = 0.7    ; Same as before, for depth.
;- Shadows capture exclusions
CastStaticObjects = 1           ; Set 0 to disable shadows from static objects (such as buildings). It doesn't make much sense, but here's the option.
CastDynamicObjects = 1          ; Set 0 to disable shadows from dynamic objects (such as lampposts). Disabling is useful to improve performance for low-end PCs. See also "CullFarSmallObjects".
CastVehicles = 1                ; Set 0 to disable shadows from vehicles. It significantly improves performance, especially in non-optimized HD vehicles. In the future may have an option to use the internal vehicle shadow mesh instead.
CastVehiclesLOD = 1             ; Set 0 to disable shadows from LOD vehicles (distant). It doesn't improve performance that much because the LODs are very optimized.
CastPeds = 1                    ; Set 0 to disable shadows from skinned models (player, peds).
CastLODs = 1                    ; Set 0 to disable shadows from LOD objects (distant). Generally is not a good idea.
CullFarSmallObjects = 1         ; Set 1 to not render shadows for small objects that are far away from the camera. It improves performance with almost no noticeable visual change.
;- Vanilla shadows
NoPedLowShadows = 0        ; Set 1 to disable low graphics shadows from peds.
NoVehicleLowShadows = 1    ; Set 1 to disable low graphics shadows from vehicles.

[SMAA]
Enabled = 1            ; Set 1 to enable Subpixel Morphological Antialiasing, an excellent anti-aliasing algorithm to replace MSAA, because, for technical reasons, MSAA (the original game AA) is not compatible with this mod, and MSAA is also more resource-intensive and causes artifacts in high-poly models, such as HD cars.
DebugMode = 0
EdgeDetectionType = 1
Preset = 2             ; 0 = Low; ... 3 = Ultra

[SimulateHDR]
Enabled = 0                     ; Set 1 to enable an excellent postFX shader that simulates HDR color rendering, and applies tone mapping to it, so the game's colors are more realistic, resembling those of modern games. It also applies realistic bloom and other fine adjustments to color, contrast etc.
DebugMode = 0
;- Tonemap
Tonemap = 1                     ; Tonemap to use: 0 = Timoty; 1 = ACES
InverseTonemap = 3              ; How HDR is simulated: 0 = Off; 1 = Luma; 2 = Color; 3 = Max color brightness
ColorBrightnessExtract = 0.5
MiddleGreyValue = 0.256
WhitePoint = 1.1
HDR_Power_Day = 0.4
HDR_Power_Night = 0.6
;- Eye adaptation
EyeAdaptation = 0
EyeAdaptation_Speed = 0.2
EyeAdaptation_SeekRadius = 0.5
;- Adjustments
Exposure_Day = 1.0              ; Basically the screen brightness (for day)
Exposure_Night = 0.0            ; Idem (for night)
Contrast_Day = 1.0
Contrast_Night = 1.05
Gamma = 1.4
Saturation = 1.3
;- Bloom
Bloom_Intensity_Day = 0.05
Bloom_Intensity_Night = 0.2
Bloom_Power = 0.5
Bloom_Curve = 2.0
Bloom_Spread = 1.25
Bloom_Dither = 0.125
Bloom_Saturation = 0.5
Bloom_Cutoff = 0.25

[SSAO]
Enabled = 0            ; Set 1 to enable Screen Space Ambient Occlusion (add shading to corners, crevices etc)
Sharpness = 0.3
BlurSteps = 9
LumLower = 0.3
LumUpper = 0.6
FadeStart = 0.6
FadeEnd = 0.9
BaseBias = 0.004
NormalBias = 0.002
Samples = 16
SamplingRange = 30.0
Darkening = 1.7
Brightening = 1.0
DebugMode = 0

[HBAO]
Enabled=1
DebugMode=0
Samples=1
SamplingRange=4.0
Amount=5.0
Amount_InteriorMult=0.5
Clamp=0.1
Attenuation=0.02
Sharpness=0.7
BlurSteps=7
TexScale=1.0
FadeStart=0.7
FadeEnd=0.9

[SunRays]
Enabled = 1               ; Set 1 to enable a kind of lensflare/godray in the sun, which is occluded by the camera contents.
quality = 1
godraysDensity = 0.95
godraysWeight = 0.65
godraysDecay = 0.94
godraysThreshold = 0.75
haloEnabled = 1.0
haloSize = 1.0

[SimpleBloom]
Enabled = 0             ; Set 1 to enable a simple version of the bloom effect (from bright surfaces). Notice that "SimulateHDR" also includes bloom, but more advanced and realistic, so don't use together.
IntensityMaster = 3.0
IntensityDay = 0.2
IntensityNight = 1.0
Threshold = 0.4
BlurSize = 2.0
Downscale = 2

[SimpleSky]
Enabled = 1    ; Replaces the game sky with a simple dithered shader, similar to the original one but much smoother.

[SoftParticles]
Enabled = 1      ; Set 1 to enable soft particles, which fixes for example the sharp cutting of dust, smoke, and fire on the ground, so all the particle effects in the game will have a smooth feel on the surfaces.
Softness = 0.7

; For testing proposes.
[DebugBuffers]
Enabled = 0
Mode = 1

[Other]
PlayerMipMaps = 0    ; Set 1 to automatically generated mipmapping for player textures, which fixes texture aliasing specially for HD player textures such as Proper Player Retex. Disabled by default because vanilla textures don't work well (there are lines on the head and face; also bugs some .txd files (even vanilla ones), which makes body parts invisible. Fixed by reimporting the textures with MagicTXD).

[Debug]
DebugTextures = 0    ; Set 1 to show debug textures to screen, such as shadow maps, for testing.
MeshNormals = 0
ForceWindShader = 0
