; Enable = 1 , Disable = 0

[SIREN]
Model = COPSIREN 
Duration = 3000 ; Duration of Siren. You can set 65500 as optional.

[HALL]
Model = SWEETSHALL2 

[GOO]
ID1 = 17998 ; Green Glow object id
ID2 = 17999 ; Green corona id