;Delay befor going into hiding phase
[Delay1]
Level1=10000
Level2=15000
Level3=20000
Level4=25000
Level5=30000
Level6=35000

;Hiding phase
[Delay2]
Level1=30000
Level2=35000
Level3=40000
Level4=45000
Level5=50000
Level6=55000

[SightDist]
Level1=50
Level2=55
Level3=60
Level4=65
Level5=70
Level6=75

[Settings]
;Lighting will affect cop sight range
LightingAffectsSight=1

;Lighting will affect hiding time/delay
LightingAffectsTime=1

;This settigs change how fast the hiding bar will fill in dark and bright areas.
;Lower the value to make the bar fill slower. Works only if LightingAffectsTime
;is set to 1.
TimerAdjDarkArea=30
TimerAdjBrightArea=20

;If this is enabled (1) then wanted level will be decreased by 1 instead of going on parole or dropping
;it immediately
LowerWantedBy1=1

;Set how successful hiding ends
; 1 - drop wanted immediately
; 2 - go on parole
HowHidingEnds=2

;Show some debug info
ShowDebugInfo=0

;Show fill bar, set to 0 to disable.
ShowFillBar=0
;Show icon near fill bar, set to 0 to disable.
ShowIcon=0

;Player blip changes color when hiding or in dark places
BlipColorChange=1

;Fill bar position
BarPosX=579.0
BarPosY=150.0