[Settings]
Progress Mode = 1		# 0 - Reset Progress during the restart game or a loading saved game
				# 1 - Saving progress. (You can manually clear the Progress.ini file. Just delete 					# the entire contents of the Progress.ini file)

Volume = 1.0			# 0.0 - 1.0
