# MedicalKit REMAKE 2.5
# Authors: Neon, MKKJ (original concept)

[Weapon Settings]
WeaponId = 90		# (12) Weapon ID to be used as a medical kit.
WeaponModel = 12535	# (323) Weapon model id to be used as a medical kit.

[Healing Mechanic]
LifeToHeal = 100.0	# (100.0) Percentage of the maximum life for heal, and minimum life to be able to use the kit.
TimeToHeal = 2500       # (2500) Time in milliseconds to heal. Using values above the defaults works, but bug the animation.

[Ambulance]
GetAmbulanKit = 1	# (0|1) Win a medical kit when entering an ambulance if you don't have a weapon occupying the slot.

				

