[MAIN]
#Rubbish alpha level at day (default 128) | Прозрачность мусора днём (По умолчанию 128)
alpha=96

#Rubbish alpha level at night (default 64), it will change smoothly from day value | Прозрачность мусора ночью (По умолчанию 64), оно плавно сменит прозрачность когда наступит день
nightalpha=64

#Total grand count of rubbish sheets, maximum - 512, Default - 64 | Общее количество мусора, максимум - 512, По умолчанию - 64
num_rubbish_sheets=32

#Rubbish max view distance (VC - 23.0, III - 18.0) | Дальность прорисовки мусора (Вайс сити - 23.0, GTA III - 18.0)
rubbish_max_dist=46.0

#Rubbish fade distance (VC - 20.0, III - 16.5) | Дальность плавного исчезания мусора (Вайс сити - 20.0, GTA III - 16.5)
rubbish_fade_dist=40.0

#Down below, you can add your own rubbish! Where [RUBBISHx] (x is a number) rubbish ID,
#where texture is texture name in rubbishSA.txd,
#where heightscale is stretchiness,
#where widthscale is rubbish size(scale).
#where ZonesToNotAppearIn - is a zone GXT key where rubbish shouldn't appear. (https://docs.sannybuilder.com/scm-documentation/sa/zones)

#Ниже, вы можете добавить свой мусор! Где [RUBBISHx] (x — число) идентификатор мусора,
#где texture — это имя текстуры в rubbishSA.txd,
#где heightscale — это растяжение мусора
#где widthscale — размер (масштаб) мусора. 
#где ZonesToNotAppearIn - GXT ключ зоны которой лист не должен появляться. (https://docs.sannybuilder.com/scm-documentation/sa/zones)
[RUBBISH0]
texture=newspaper01_64		
heightscale=1.0				
widthscale=1.0				
#ZonesToNotAppearIn=LA

[RUBBISH1]
texture=newspaper02_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH2]
texture=newspaper03_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH3]
texture=newspaper04_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH4]
texture=newspaper05_64		
heightscale=1.0
widthscale=0.9	
#ZonesToNotAppearIn=LA			

[RUBBISH5]
texture=newspaper06_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH6]
texture=newspaper07_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH7]
texture=newspaper08_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH8]
texture=newspaper09_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH9]
texture=newspaper10_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH9]
texture=gameleaf01_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH10]
texture=gameleaf02_64
heightscale=3.5
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH11]
texture=gameleaf03_64
heightscale=3.5
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH12]
texture=gameleaf04_64
heightscale=3.5
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH13]
texture=gameleaf05_64
heightscale=1.0
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH14]
texture=gameleaf06_64
heightscale=3.5
widthscale=1.0
#ZonesToNotAppearIn=LA

[RUBBISH15]
texture=gameleaf07_64
heightscale=1.0
widthscale=0.9
#ZonesToNotAppearIn=LA

[RUBBISH16]
texture=gameleaf08_64
heightscale=1.8
widthscale=1.8
#ZonesToNotAppearIn=LA