[Settings]
Key = 74
Key Gamepad = 19

[Car Exception]
#445 = 2	# (Car ID) = 1 - for Exception, 2 - convertible; just delete the line if you don't need to
429 = 2
536 = 2
480 = 2
528 = 1
533 = 2
604 = 1
411 = 1
502 = 1
503 = 1
494 = 1
601 = 1
605 = 1
567 = 2
439 = 2
574 = 1
555 = 2


