# Property buy settings file for "Buy Property Mod by Junior_Djjr"
# https://www.mixmods.com.br/2020/07/buy-property-mod-comprar-propriedades/
# Avoid editing this .ini if you already bought this property on your saved game.
# Property author: ohnoo, Junior_Djjr

[Settings]
# Buy icon. Dollar sign when bought.
BuyCoord = -1983.5662 2197.5217 1.98

# Set "1" if you don't want the dollar sign. Useful for safe houses. Required to set "SavePickupCoord" then.
OnlySavePickup = 1

# If set, it will create a save pickup. Comment (#) or set 0.0 0.0 0.0 to disable it.
SavePickupCoord = -1996.303 2193.286 2.889

# Save-load player heading angle.
Angle = 180.0

# Unlocked after: 0 = Los Santos (always); 1 = Countryside; 2 = San Fierro; 3 = Desert; 4 = Las Venturas
UnlockedAfter = 3

# Buy price.
Price = 50000

# Max profit over the time.
#Profit = 0

# Radar icon when bought. Comment (#) or set -1 to disable it. Tip: 35 for save.
RadarIcon = 35

# Camera coord for buy scene. Comment (#) or set 0.0 0.0 0.0 to disable it.
CamCoord = -1975.859 2147.405 13.5579

# Where the camera points for buy scene. Comment (#) or set 0.0 0.0 0.0 to disable it.
CamPoint = -1998.6606 2186.5942 3.2568

# Interior (ENEX) name to enable acess when bought. Comment (#) to disable it.
#EnableInterior =
