------------------------ Manual Driveby Refixed v.26.01.22 -----------------------

; During gameplay, type "MDRRELOAD" to reload the settings

[MAIN]                      ; Some general settings

DisableOnSAMP = 0           ; 0 = Enabled. // 1 = The mod automatically deactivates itself when playing SAMP. 

DrivebyControlType = 5      ; Affects gamepad only. Values greater than 2 disable sidelook function
                            ; 0 = L1 aim and shoot. // 1 = L1 aim and shoot, Circle finish. // 2 = L1 aim, Circle shoot. // 3 = L2 aim, R2 shoot. // 4 = R2 aim, L2 shoot.
                            ; For ginput layout 2: // 5 = L1 aim, R1 shoot. // 6 = R1 aim, L1 shoot.

DrivebyAimButton = RMB      ; Ignored by gamepad. Type key names, such as G, or + (it detects common keys) or virtual keycodes greater than 9

PreLoadIFP = 1              ; Fixes activation delay caused by ifp loading
DisableBikeWeakPoint = 1    ; Disables petrol tank weak point while aiming on a bike, so avoiding exploding your own bike

NoDrivingWhileAiming = 0    ; Disables driving ability while aiming: 0 = Off. // 1 = On all vehicles. // 2 = Only on bikes.
PrepareThrowAnim = 1        ; Set to 0 if you don't use any mod that fixes vanilla car animations (Links in ReadMe file)

CloseWindowsAgain = 1       ; Rolls up the windows of all closed and undamaged doors when leaving the car
WindshieldMode = 1          ; Breaks windshield when shooting forward: 0 = Off. // 1 = With new animations. // 2 = With old animations.

FixPedReactions = 2         ; Makes peds react to being targeted, similar to aiming on foot. Also allows recruiting gang members
                            ; Set to 2 for being able to provoke gang wars with driveby
RecruitBlip = 1             ; Creates a green cone above targeted grove street members if they are available for recruitment
_______________________________________________________________________________________________________________________________________

[WEAPONSWITCH]              ; Controls for switching weapons

DPadButtonsMode = 2         ; Affects gamepad only. // 0 = Off. // 1 = Left and Right. // 2 = Up and Down.

SideLookButtons = 0         ; E and Q on keyboard (with default game menu settings). L2 and R2 on gamepad. Disables sidelook function. Ignored in helis and planes
                            ; 0 = Off. // 1 = On. // 2 = Only while aiming.

UseMouseWheel = 2           ; 0 = Off. // 1 = On. // 2 = Only while aiming.

NextWeaponKey = 3           ; Type key names, such as G, or + (it detects common keys) or virtual keycodes greater than 9
LastWeaponKey = 1

EnableOnStory = 1           ; Enables weapon switching during driveby scenes in missions. ("Just Business" and "End of the Line")
_______________________________________________________________________________________________________________________________________

[WEAPONSETTINGS]

---- Availability of weapon classes based on vehicle subclasses ----

; Format: 'InstantHit' (= Guns) / 'Projectile' (= Grenades etc.) / 'AreaEffect' (= Spraycan etc.)
; With setting 0/0/0, the vehicles are treated like those in the exception list   

Cars =   1/1/1
Bikes =  1/1/1
Boats =  1/1/1
Helis =  1/1/1
Planes = 1/1/1
Trains = 1/1/1

---- Availability and shoot rate of each weapon in the vehicles based on weapon skill levels ----

FixShootRateOfNPC = 1       ; Applies the configured shoot rates to NPC drivebys, too. Normally, there's only one static shoot rate for every weapon during a driveby

; Add weapons to the list below you want to disable. 1.0 = enable by skill level, -1.0 = disable by skill level
; Weapon IDs: https://wiki.multitheftauto.com/wiki/Weapons 

; Format: 'Weapon ID' (not model ID) = Shoot rate by skill level: 'Poor' / 'Gangster' / 'Hitman'

; If there aren't any skill levels for a specific weapon (e.g. Minigun) then the value in the middle is applied
; For throwable weapons, the right and left values affect the throwing distance: Left for minimal, right for maximal distance

; Range: 0.01 - 9.99
; Special values: -1.0 = weapon not selectable. // 0.00 = weapon selectable but not usable. // 1.00 = same shootrate as on foot.

Default = 1.00 / 1.00 / 1.00  ; Setting for all guns that aren't configured below.
                              ; If you have more to disable than enable, then set -1.0 / -1.0 / -1.0 here and define all desired weapons manually below.

34 = 0.00 / -1.0 / 0.00       ; Sniper

#35 = 0.00 / 0.10 / 0.00       ; with "Rocket Launcher Third Person" Mod by LKboss
37 = 0.00 / 1.00 / 0.00       ; Flamethrower

41 = 0.00 / 1.00 / 0.00       ; Spraycan
42 = 0.00 / 1.00 / 0.00       ; Extinguisher

16 = 0.32 / 1.00 / 0.70       ; Grenade
17 = 0.08 / 1.00 / 0.70       ; Teargas
18 = 0.18 / 1.00 / 0.60       ; Molotov
39 = 0.06 / 1.00 / 0.40       ; Satchel
40 = 0.00 / 1.00 / 0.00       ; Detonator

; These are commented out because it's my personal config. Delete the # if you want a more realistic and rewarding experience
#25 = -1.0 / -1.0 / 1.00       ; Shotgun
#27 = -1.0 / 1.00 / 1.00       ; Combat Shotgun
#30 = -1.0 / 1.00 / 1.00       ; AK-47
#31 = -1.0 / -1.0 / 1.00       ; M4

_______________________________________________________________________________________________________________________________________

[CAMERA]                        

; The settings with the format below follow your respective vehicle camera mode
; -1.0 is an actual value here, so to disable you would need to comment out the line
; Format: 'Near' / 'Middle' / 'Far'

DistCar =    5.00 / 10.0 / 17.0   ; (6.0) Camera distance for cars according to the current vehicle camera mode
DistBike =   2.80 / 4.40 / 17.3   ; (3.5) for bikes 
HeightCar =  0.50 / 0.60 / 0.70   ; (0.4) Camera height for cars
HeightBike = 0.20 / 0.20 / 0.20   ; (0.2) for bikes
TweakFOV =   70.0 / 70.0 / 70.0   ; (70.0) FOV (zoom depth)

RestoreDistance = 0               ; Camera always returns to this vehicle camera mode: 0 = Previous mode. // 1 = Near. // 2 = Middle. // 3 = Far.

JumpcutRestore = 1                ; Instantly moves the camera behind the vehicle after aiming. Values greater than 1 are considered as time in ms for screen fading
JumpcutCarSpeed = 8.0             ; Camera jumps only if the car speed is equal or higher than this value

FPCameraCentering = 1             ; For first person mod. Rotates the camera to the front after driveby. Set 2 for additional fading effect
KeepAiming = 0                    ; Keep in driveby mode until you press the aim button again. // 0 = Off. // 1 = On. // 2 = In first person view only.

FreeLineOfSight = 0               ; Makes the vehicle temporarily invisible if it blocks your view too much
NoAngleLimit = 1                  ; 0 = Moving crosshair up and down is limited. // 1 = Free aiming up and down. Useful for aiming at helicopters.
_______________________________________________________________________________________________________________________________________

[EXCEPTIONS]                      ; Only vanilla driveby will be available, nitro fix will still be applied

DisableOnMission = 0              ; Set to 1 for conventional mission difficulty. Does not affect the 'EnableOnStory' setting.

; Here you can add the IDs of vehicles for which you want to disable all weapon features of this mod.
; For tanks it's automatically disabled.

407 = 1     ; Firetruck
6348 = 1   ; Skateboard from 'Skate Mod Remake'

_______________________________________________________________________________________________________________________________________

[CARSWITHOUTWINDOWS]              ; You can ignore this if you don't have crashes when aiming in specific vehicles.

; Some users reported crashes when aiming in vehicles without windows — this list prevents that.
; You can add cars here as well. Combined with the default list, the mod already detects all vanilla vehicles.

; 1 = No door windows. // 2 = No door windows and no windshield

406 = 2     ; Dumper
530 = 2     ; Forklift
485 = 2     ; Baggage
568 = 1     ; Bandito
457 = 1     ; Caddy
533 = 1     ; Feltzer
439 = 1     ; Stallion
429 = 1     ; Banshee
480 = 1     ; Comet
555 = 1     ; Windsor
536 = 1     ; Blade
575 = 1     ; Broadway
567 = 1     ; Savanna
592 = 1     ; Andromada
577 = 1     ; AT-400
553 = 1     ; Nevada
519 = 1     ; Shamal
